---

version: '3.7'
services:
  nci2021_lab:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8090:8080
    networks:
      - labnetwork
    environment:
      - INFURA_TOKEN=b537bfe7189243cebb6ee42982464310
      - CONTRACT_ADDRESS=0xec00a4a48ee652daddff6a7e92ddca490a06cfac
      - OWNER_ADDRESS=0x6ad22f5492c5baBBEA092F69Ff994dC77bCC65b4
      - SUPER_SECRET_PRIVATE_KEY=b51b72ac6eb5fbe369079e96d638f9a847156db8eb4491ce842f6de2963d8968
networks:
  labnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/24