---

version: '3.7'
services:
  nci2021_lab:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8090:8080
    networks:
      - labnetwork
    environment:
      - INFURA_TOKEN=b537bfe7189243cebb6ee42982464310
      - CONTRACT_ADDRESS=0x173Ef16855c9be321BA845C9426455c05212bC3d
      - OWNER_ADDRESS=0x8B3DffAFC82610Eb0EeD76D9b8D410F8067841Fa
      - SUPER_SECRET_PRIVATE_KEY=ee7e8abce70c2d7bd598269349292bc3098c5df504fc0dbfc91b7771654b4410clear
networks:
  labnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.60.0.0/24